name: Publish

on:
  push:
    branches:
      - dev

jobs:
  publish:
    if: ${{ startsWith(github.event.head_commit.message, 'chore(release):') }}
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: yarn --frozen-lockfile
      - run: |
          rm -rf node_modules/.cache
          yarn build
          yarn build-docs
          yarn test
          if $IS_BETA; then
            yarn publish-package-next
          else
            yarn publish-package
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          IS_BETA: ${{ contains(github.event.head_commit.message, 'beta') }}
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/.vuepress/dist
          TARGET_FOLDER: v0
      - run: yarn haoma run scripts/create_github_release.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn notify-dingtalk
        env:
          D_ACCESS_TOKEN: ${{ secrets.DINGTALK_ACCESS_TOKEN }}
          D_SECRET: ${{ secrets.DINGTALK_SECRET }}
