name: Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ hashFiles('yarn.lock') }}
      - if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: yarn --frozen-lockfile
      - run: |
          rm -rf node_modules/.cache
          yarn build
          yarn test
